# Generated by Django 3.2.8 on 2021-11-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TheMovieDBConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smallestImageSize', models.TextField()),
                ('baseURL', models.TextField()),
                ('dateRetrieved', models.DateTimeField()),
            ],
        ),
    ]
