# Generated by Django 3.2.8 on 2021-11-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='themoviedbconfiguration',
            name='bestPosterSize',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
