# Generated by Django 3.2.8 on 2021-12-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_themoviedbconfiguration_bestpostersize'),
    ]

    operations = [
        migrations.AddField(
            model_name='themoviedbconfiguration',
            name='still_size',
            field=models.TextField(default='original'),
            preserve_default=False,
        ),
    ]
